app-config:
  web-flux:
    h2-console-port: 8081
    log-enabled: true

spring:
  profiles:
    active: default
  devtools:
    livereload:
      enabled: true

logging:
  config: classpath:logback-spring.xml
# info가 Default
#    root: info
# category 별로 로깅 레벨 다르게 설정하고 싶으면
#    test : debug
